version: '3.4'
services:
  controlapp.api:
    image: ${DOCKER_REGISTRY-}controlappapi
    build:
      context: .
      dockerfile: './1-API/ControlApp.API/Dockerfile'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - mongodb
    networks:
      - controlapp-network
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - controlapp-network

networks:
  controlapp-network:
    driver: bridge

volumes:
  mongodb_data: